### ISSUE TITLE
It runs nice

### ISSUE THREAD

**Issue by sneccc** [GalaX1us/Neural-Style-Transfer#1]
This runs nice !, are you considering improving the pre existing algos to increase fidelity ? 

This implementations for example starts with low res and it scales up , ends up with better quality https://github.com/crowsonkb/style-transfer-pytorch

Also i was wondering if doing a color transfer first would improve since it will make it more similar to begin with.

There is a nice wiki with several tests and info on style transfer https://github.com/jcjohnson/neural-style/wiki/Improving-Output-Image-Quality and https://github.com/ProGamerGov/Neural-Tools/wiki

There is also this repo that claims to be better, but its a little slow and cant do other size ratios https://github.com/aigagror/style-transfer-quality

**Comment by nathanbonada** [comment]
Thank you for your feedback, I will go and have a look at the resources you propose !
